# Generated by Django 6.0.2 on 2026-02-22 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. Main Office, Warehouse A", max_length=100
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        help_text="2-letter US state abbreviation", max_length=2
                    ),
                ),
                ("zip_code", models.CharField(max_length=10)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Address",
                "verbose_name_plural": "Saved Addresses",
                "db_table": "saved_addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
