# Generated by Django 6.0.2 on 2026-02-22 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. Light Package, Standard Box", max_length=100
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, help_text="Length in inches", max_digits=6
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, help_text="Width in inches", max_digits=6
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, help_text="Height in inches", max_digits=6
                    ),
                ),
                (
                    "weight_lb",
                    models.IntegerField(default=0, help_text="Weight in pounds"),
                ),
                (
                    "weight_oz",
                    models.IntegerField(default=0, help_text="Weight in ounces"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Package",
                "verbose_name_plural": "Saved Packages",
                "db_table": "saved_packages",
                "ordering": ["-created_at"],
            },
        ),
    ]
