# Generated by Django 6.0.2 on 2026-02-22 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original uploaded CSV filename", max_length=255
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("valid_records", models.IntegerField(default=0)),
                ("invalid_records", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("shipping_selected", "Shipping Selected"),
                            ("purchased", "Purchased"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "label_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("letter", "Letter / A4 (8.5x11)"),
                            ("4x6", "4x6 inch (Thermal)"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Batch",
                "verbose_name_plural": "Shipment Batches",
                "db_table": "shipment_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(help_text="Original row number in CSV"),
                ),
                (
                    "from_first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "from_last_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "from_address1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "from_address2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("from_city", models.CharField(blank=True, default="", max_length=100)),
                ("from_state", models.CharField(blank=True, default="", max_length=2)),
                ("from_zip", models.CharField(blank=True, default="", max_length=10)),
                ("from_phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "to_first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "to_last_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "to_address1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "to_address2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("to_city", models.CharField(blank=True, default="", max_length=100)),
                ("to_state", models.CharField(blank=True, default="", max_length=2)),
                ("to_zip", models.CharField(blank=True, default="", max_length=10)),
                ("to_phone", models.CharField(blank=True, default="", max_length=20)),
                ("weight_lb", models.IntegerField(blank=True, null=True)),
                ("weight_oz", models.IntegerField(blank=True, null=True)),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("item_sku", models.CharField(blank=True, default="", max_length=100)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("is_valid", models.BooleanField(default=False)),
                (
                    "from_address_verified",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="unverified",
                        max_length=12,
                    ),
                ),
                (
                    "to_address_verified",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="unverified",
                        max_length=12,
                    ),
                ),
                (
                    "shipping_service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("priority", "Priority Mail"),
                            ("ground", "Ground Shipping"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="shipments.shipmentbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Record",
                "verbose_name_plural": "Shipment Records",
                "db_table": "shipment_records",
                "ordering": ["row_number"],
            },
        ),
    ]
